/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package github.artika.galeria;

import java.awt.Component;
import java.awt.Image;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JList;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;

/**
 *
 * @author ciclot
 */
public class JFrameGaleria extends javax.swing.JFrame {

    public static final String  RUTA_BANCO_1 = "src\\bancos\\Banco 1";
    public static final String  RUTA_BANCO_2 = "src\\bancos\\Banco 2";
    public static final String  RUTA_BANCO_3 = "src\\bancos\\Banco 3";
    
    private String rutaTemp = "";
   
    
    public JFrameGaleria() {
        initComponents();
        setLocationRelativeTo(null);
        jScrollPaneCarpeta.getViewport().setOpaque(false); // Para quitar el fondo de JScrollPane
        jListArchivos.setCellRenderer(renderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanelDerecho = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jSplitPaneBotones = new javax.swing.JSplitPane();
        jButtonAnterior = new javax.swing.JButton();
        jButtonSiguiente = new javax.swing.JButton();
        jLabelImagen = new javax.swing.JLabel();
        jScrollPaneCarpeta = new javax.swing.JScrollPane();
        jListArchivos = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCarpetas = new javax.swing.JMenu();
        jMenuItemBanco1 = new javax.swing.JMenuItem();
        jMenuItemBanco2 = new javax.swing.JMenuItem();
        jMenuItemBanco3 = new javax.swing.JMenuItem();
        jMenuEdicion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ArturFytsyk - GALERIA DE FOTOS");
        setResizable(false);

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 255, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(240, 106, 58));

        jPanelDerecho.setMaximumSize(new java.awt.Dimension(1093, 715));
        jPanelDerecho.setMinimumSize(new java.awt.Dimension(1093, 715));
        jPanelDerecho.setOpaque(false);

        javax.swing.GroupLayout jPanelDerechoLayout = new javax.swing.GroupLayout(jPanelDerecho);
        jPanelDerecho.setLayout(jPanelDerechoLayout);
        jPanelDerechoLayout.setHorizontalGroup(
            jPanelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1343, Short.MAX_VALUE)
        );
        jPanelDerechoLayout.setVerticalGroup(
            jPanelDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 895, Short.MAX_VALUE)
        );

        jPanel1.setOpaque(false);

        jSplitPaneBotones.setBackground(new java.awt.Color(0, 255, 204));
        jSplitPaneBotones.setDividerLocation(275);

        jButtonAnterior.setBackground(new java.awt.Color(5, 162, 131));
        jButtonAnterior.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButtonAnterior.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAnterior.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButtonAnterior.setLabel("ANTERIOR");
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });
        jSplitPaneBotones.setLeftComponent(jButtonAnterior);

        jButtonSiguiente.setBackground(new java.awt.Color(5, 162, 131));
        jButtonSiguiente.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButtonSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSiguiente.setText("SIGUIENTE");
        jButtonSiguiente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguienteActionPerformed(evt);
            }
        });
        jSplitPaneBotones.setRightComponent(jButtonSiguiente);

        jLabelImagen.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabelImagen.setMaximumSize(new java.awt.Dimension(1093, 715));
        jLabelImagen.setMinimumSize(new java.awt.Dimension(1093, 715));
        jLabelImagen.setPreferredSize(new java.awt.Dimension(1093, 715));

        jScrollPaneCarpeta.setBackground(new java.awt.Color(240, 106, 58));

        jListArchivos.setBackground(new java.awt.Color(255, 204, 204));
        jListArchivos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jListArchivos.setFont(new java.awt.Font("Candara Light", 1, 14)); // NOI18N
        jListArchivos.setForeground(new java.awt.Color(255, 255, 255));
        jListArchivos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListArchivos.setOpaque(false);
        jListArchivos.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jListArchivos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jListArchivosFocusLost(evt);
            }
        });
        jListArchivos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jListArchivosKeyPressed(evt);
            }
        });
        jListArchivos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListArchivosValueChanged(evt);
            }
        });
        jScrollPaneCarpeta.setViewportView(jListArchivos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPaneCarpeta, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPaneBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneCarpeta, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSplitPaneBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165)
                .addComponent(jPanelDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(807, 807, 807))
        );

        jMenuCarpetas.setBackground(new java.awt.Color(255, 161, 147));
        jMenuCarpetas.setText("Carpetas");

        jMenuItemBanco1.setText("Banco 1");
        jMenuItemBanco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBanco1ActionPerformed(evt);
            }
        });
        jMenuCarpetas.add(jMenuItemBanco1);

        jMenuItemBanco2.setText("Banco 2");
        jMenuItemBanco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBanco2ActionPerformed(evt);
            }
        });
        jMenuCarpetas.add(jMenuItemBanco2);

        jMenuItemBanco3.setText("Banco 3");
        jMenuItemBanco3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBanco3ActionPerformed(evt);
            }
        });
        jMenuCarpetas.add(jMenuItemBanco3);

        jMenuBar1.add(jMenuCarpetas);

        jMenuEdicion.setText("Edición");
        jMenuBar1.add(jMenuEdicion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1192, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Al llegar al principio si se pulsa la seleccion pasa al final
    
    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        if (!"".equals(rutaTemp)){
            int posActual = jListArchivos.getSelectedIndex();
            if (posActual != 0){
                jListArchivos.setSelectedIndex(posActual - 1);
            }else{
                jListArchivos.setSelectedIndex(jListArchivos.getModel().getSize() - 1);
            }
        }
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private ArrayList<String> listarArchivos(String ruta){
        ArrayList<String> listaArchivos = new ArrayList<>();

        File folder = new File(ruta);
        File[] files = folder.listFiles();

        if (files != null) {
            for (File file : files) {
                if (file.getName().toLowerCase().endsWith(".jpg")){
                    listaArchivos.add(file.getName());
                }
                
            }
        }
        return listaArchivos;
    }
    
    private void anyadirListaAJList(ArrayList<String> listaArchivos){
        DefaultListModel<String> modelo = new DefaultListModel<>();

        for (String archivo : listaArchivos) {
            modelo.addElement(archivo);
        }
        
        jListArchivos.setModel(modelo);
    }
    
    
    
    // Mostrado de archivos en jListArchivos al usar el menu Carpetas
    
    private void jMenuItemBanco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBanco1ActionPerformed
        anyadirListaAJList(listarArchivos(RUTA_BANCO_1));
        jListArchivos.setSelectedIndex(0);
        rutaTemp = RUTA_BANCO_1;
        redimensionarImagenSegunLabel();
    }//GEN-LAST:event_jMenuItemBanco1ActionPerformed

    private void jMenuItemBanco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBanco2ActionPerformed
        anyadirListaAJList(listarArchivos(RUTA_BANCO_2));
        jListArchivos.setSelectedIndex(0);
        rutaTemp = RUTA_BANCO_2;
        redimensionarImagenSegunLabel();
    }//GEN-LAST:event_jMenuItemBanco2ActionPerformed

    private void jMenuItemBanco3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBanco3ActionPerformed
        anyadirListaAJList(listarArchivos(RUTA_BANCO_3));
        jListArchivos.setSelectedIndex(0);
        rutaTemp = RUTA_BANCO_3;
        redimensionarImagenSegunLabel();
    }//GEN-LAST:event_jMenuItemBanco3ActionPerformed

    private void redimensionarImagenSegunLabel(){
        ImageIcon imagenIcon = new ImageIcon(rutaTemp + "\\" + jListArchivos.getSelectedValue());
        Image imagen = imagenIcon.getImage();
        Image escalaImagen = imagen.getScaledInstance(jLabelImagen.getWidth(), jLabelImagen.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imagenEscalada = new ImageIcon(escalaImagen);
        jLabelImagen.setIcon(imagenEscalada);
    }
    // Mostrado de imagenes en el jLabelImagenes al seleccionar un item de la JListArchivos
    
    private void jListArchivosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListArchivosValueChanged
        if (!evt.getValueIsAdjusting()){
            redimensionarImagenSegunLabel();
            SwingUtilities.invokeLater(() -> { //Ejecuta la siguiente orden despues de que se actualice el jList
                jListArchivos.ensureIndexIsVisible(jListArchivos.getSelectedIndex());
            });
        }
    }//GEN-LAST:event_jListArchivosValueChanged

    // Al llegar al final si se pulsa la seleccion pasa al principio
    
    private void jButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguienteActionPerformed
        if (!"".equals(rutaTemp)){
            int posActual = jListArchivos.getSelectedIndex();
            int posFinal = jListArchivos.getModel().getSize() - 1;
            if (posActual != posFinal){
                jListArchivos.setSelectedIndex(posActual + 1);
            }else{
                jListArchivos.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_jButtonSiguienteActionPerformed

    // Cada vez que usamos los botones queremos que no se nos vaya el focus del jListArchivos
    
    private void jListArchivosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jListArchivosFocusLost
        jListArchivos.requestFocus();
    }//GEN-LAST:event_jListArchivosFocusLost
   
    private void jListArchivosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jListArchivosKeyPressed
        if (!rutaTemp.equals("")){
            // Le quitamos la funcionalidad que tiene por defecto JList en las teclas up y down
            InputMap inputMap = jListArchivos.getInputMap(JComponent.WHEN_FOCUSED);
            inputMap.put(KeyStroke.getKeyStroke(evt.VK_UP, 0), "none");
            inputMap.put(KeyStroke.getKeyStroke(evt.VK_DOWN, 0), "none");
        
            int code = evt.getKeyCode();
            int posicionActual = jListArchivos.getSelectedIndex();
            int ultimoElemento = jListArchivos.getModel().getSize() - 1;
            
            if (code == KeyEvent.VK_UP && posicionActual == 0){
                jListArchivos.setSelectedIndex(ultimoElemento);
            }else if (code == KeyEvent.VK_UP){
                jListArchivos.setSelectedIndex(posicionActual - 1);
            }else if (code == KeyEvent.VK_DOWN && posicionActual == ultimoElemento){
                jListArchivos.setSelectedIndex(0);
            }else if (code == KeyEvent.VK_DOWN ){
                jListArchivos.setSelectedIndex(posicionActual + 1);
            }
        }
    }//GEN-LAST:event_jListArchivosKeyPressed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameGaleria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameGaleria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameGaleria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameGaleria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameGaleria().setVisible(true);
            }
        });
    }
    
    // Un Override para poner transparente los elementos del JList
    
    DefaultListCellRenderer renderer = new DefaultListCellRenderer() {
    @Override
        public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            setOpaque(false); // Hace transparente el fondo del texto
            return this;
        }
    };
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonSiguiente;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JList<String> jListArchivos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCarpetas;
    private javax.swing.JMenu jMenuEdicion;
    private javax.swing.JMenuItem jMenuItemBanco1;
    private javax.swing.JMenuItem jMenuItemBanco2;
    private javax.swing.JMenuItem jMenuItemBanco3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDerecho;
    private javax.swing.JScrollPane jScrollPaneCarpeta;
    private javax.swing.JSplitPane jSplitPaneBotones;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
